### ISSUE TITLE
[bug fix] study for pl

### ISSUE THREAD

**Issue by alevenberg** [cfiutak1/JavaPythonPrint#2]
We have a final at 12 tomorrow

**Comment by cfiutak1** [comment]
12:50*

**Comment by cfiutak1** [comment]
![List Monster](http://s3.amazonaws.com/lyah/listmonster.png)

can you explain this pls

**Comment by alevenberg** [comment]
i think it's pretty self-explanatory

**Comment by cfiutak1** [comment]
I'm stuck on how to draw the face and flower
